-- 1. Create the 'submissions' table
CREATE TABLE public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    status TEXT DEFAULT 'Pending Review',
    title TEXT,
    abstract TEXT,
    journal_name TEXT,
    special_instructions TEXT,
    services TEXT[],
    citation_style TEXT,
    file_urls TEXT[],
    total_price NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on the submissions table
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own submissions
CREATE POLICY "Users can view their own submissions"
ON public.submissions FOR SELECT
USING (auth.uid() = user_id);

-- Policy: Users can insert their own submissions
CREATE POLICY "Users can insert their own submissions"
ON public.submissions FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Policy: Admin can view all submissions (Optional, adjust as needed)
-- Note: Replace 'your_admin_user_id' with the actual UUID of your admin user, or manage this with a separate admin role checking.
-- CREATE POLICY "Admins can view all submissions" ON public.submissions FOR SELECT USING (true);


-- 2. Create the 'manuscript_files' storage bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('manuscript_files', 'manuscript_files', true);

-- Policy: Users can upload files to their own folder inside the bucket
CREATE POLICY "Users can upload their own files"
ON storage.objects FOR INSERT
WITH CHECK (
    bucket_id = 'manuscript_files' AND
    auth.uid()::text = (storage.foldername(name))[1]
);

-- Policy: Public can read files (since it's a public bucket, we just ensure select is open)
CREATE POLICY "Public can view files"
ON storage.objects FOR SELECT
USING (bucket_id = 'manuscript_files');

-- 3. Create a 'profiles' table for admin user tracking (Optional, used in AdminDashboard.tsx)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up a trigger to auto-create a profile on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
