-- Drop and recreate submissions table
DROP TABLE IF EXISTS public.submissions;

CREATE TABLE public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    author_name TEXT,
    author_email TEXT,
    country TEXT,
    code TEXT,
    affiliation TEXT,
    message TEXT,
    journal TEXT,
    manuscript_title TEXT,
    manuscript_url TEXT,
    supplementary_url TEXT,
    status TEXT DEFAULT 'Pending Review',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own submissions (either by auth.uid or by email claim)
CREATE POLICY "Users can view their own submissions"
ON public.submissions FOR SELECT TO authenticated
USING (
    (SELECT auth.uid()) = user_id OR
    (current_setting('request.jwt.claims', true) IS NOT NULL AND (current_setting('request.jwt.claims', true)::json->>'email') = author_email)
);

-- Allow authenticated users to insert (you can tighten this to check user_id = auth.uid() if needed)
CREATE POLICY "Users can insert their own submissions"
ON public.submissions FOR INSERT TO authenticated
WITH CHECK (
    -- allow inserting if the row is owned by the auth user OR if author_email matches JWT email
    (user_id IS NULL) OR
    (user_id = (SELECT auth.uid())) OR
    (current_setting('request.jwt.claims', true) IS NOT NULL AND (current_setting('request.jwt.claims', true)::json->>'email') = author_email)
);

-- Insert bucket (be careful: direct writes to storage.buckets may be restricted)
INSERT INTO storage.buckets (id, name, public) VALUES ('manuscript_files', 'manuscript_files', true)
ON CONFLICT (id) DO NOTHING;

-- RLS policies for storage.objects bucket access
DROP POLICY IF EXISTS "Users can upload their own files" ON storage.objects;
CREATE POLICY "Users can upload their own files"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'manuscript_files');

DROP POLICY IF EXISTS "Public can view files" ON storage.objects;
CREATE POLICY "Public can view files"
ON storage.objects FOR SELECT TO public
USING (bucket_id = 'manuscript_files');
